export default [
  { slug:'clubeez', title:'Clubeez — Community & Club Platform',
    description:'Frontend Vue 3 with .NET backend integration for events, memberships, real‑time flows.',
    tech:['Vue 3','Vite','Pinia','ASP.NET'], link:'https://www.webalive.com.au/project/clubeez/' },
  { slug:'mining-bull', title:'Mining Bull — Mining Data Intelligence',
    description:'Modern Vue 3 interface for mining data discovery with performant tables and filters.',
    tech:['Vue 3','Vue Router','REST'], link:'https://www.webalive.com.au/project/mining-bull/' },
  { slug:'business-plaza', title:'Business Plaza',
    description:'ASP.NET + Angular app with auth, dashboards, and RBAC.',
    tech:['ASP.NET','Angular','JWT','SQL'], link:'https://www.webalive.com.au/project/business-plaza/' },
  { slug:'chamera', title:'Chamera',
    description:'Angular + Kendo UI on ASP.NET services with UX/perf focus.',
    tech:['ASP.NET','Angular','Kendo UI'], link:'https://www.webalive.com.au/project/chamera/' },
  { slug:'mininghub', title:'MiningHub',
    description:'Node/Express + vanilla JS for data pipelines and admin portal.',
    tech:['Node.js','Express','PostgreSQL','JS'], link:'https://mininghub.daybud.com/home' },
  { slug:'nintendo', title:'Nintendo — Internal tooling',
    description:'Vue 3 features for internal dashboards and workflows.', tech:['Vue 3','Vite','REST'] },
  { slug:'locumwest', title:'Locumwest',
    description:'Vue 3 frontend for healthcare staffing workflows with reusable components.', tech:['Vue 3','Pinia','Axios'] },
  { slug:'webalive-erp', title:'Webalive ERP',
    description:'Laravel + JS modules: inventory, invoicing, reporting with RBAC.', tech:['Laravel','PHP','MySQL','JS'] },
  { slug:'lantech', title:'Lantech',
    description:'Vue 3 components and app architecture for a B2B platform.', tech:['Vue 3','Vite','Pinia'] }
]
